Bug/sc 28952/ places bug place resolver processing (#50)
* https://app.shortcut.com/ehawk/story/28952/places-bug-place-resolver-processing-failures - switch to kotlin, get rid of ExecutorService, use coroutines in the GeoDataManager to be able to cancel processing

* https://app.shortcut.com/ehawk/story/28952/places-bug-place-resolver-processing-failures - switch to kotlin, get rid of ExecutorService, use coroutines in the GeoDataManager to be able to cancel processing

* https://app.shortcut.com/ehawk/story/28952/places-bug-place-resolver-processing-failures - gradle-wrapper.jar

* https://app.shortcut.com/ehawk/story/28952/places-bug-place-resolver-processing-failures - copilot comments

---------

Co-authored-by: Andrey Chorniy <andrey.chorniy@gmail.com>

diff --git a/.github/workflows/publish-github-release.yml b/.github/workflows/publish-github-release.yml
--- a/.github/workflows/publish-github-release.yml
+++ b/.github/workflows/publish-github-release.yml
@@ -12,6 +12,10 @@ on:
       - '**/*.gitattributes'
       - '.github/**/*'
 
+concurrency:
+  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
+  cancel-in-progress: true
+
 jobs:
   publish:
     runs-on: ubuntu-latest
@@ -19,13 +23,32 @@ jobs:
       contents: read
       packages: write
     steps:
-      - uses: actions/setup-java@v5
       - uses: actions/checkout@v5
+      - uses: actions/setup-java@v5
         with:
-          java-version: '8'
-          distribution: 'adopt'
-          server-id: dynamodb-geo-aws-sdk-2
+          java-version: '21'
+          distribution: 'temurin'
+          cache: 'gradle'
+      - uses: gradle/actions/setup-gradle@v5
+        with:
+          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
+
       - name: Publish package
-        run: mvn --batch-mode deploy
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          set +e
+          command="./gradlew :publish"
+          output=$($command 2>&1)
+          status=$?
+          set -e
+          if [ $status -eq 0 ]; then
+            echo "Published successfully $output"
+          else
+              if [[ $output == *"409"* && $output == *"Conflict"* ]]; then
+                echo "The artifact is already published $output"
+              else
+                echo "Failed to publish artifact $status, $output" >&2
+                exit 1
+              fi
+          fi
